# HEXACO
HEXACO_NUM_RESPONSES = 60
HEXACO_REVERSE_KEY_VALUE = 6

# MBTI
MBTI_NUM_RESPONSES = 70
MBTI_E_I_THRESHOLD = 5
MBTI_S_N_THRESHOLD = 10
MBTI_T_F_THRESHOLD = 10
MBTI_J_P_THRESHOLD = 10

# Attachment Styles
ATTACHMENT_STYLES_NUM_RESPONSES = 20

# Schwartz Values
SCHWARTZ_VALUES_NUM_RESPONSES = 10
